### ISSUE TITLE
I am getting issue when using to detect the characters in the keyboard 

### ISSUE THREAD

**Issue by prasanna532** [chedanix/hands_on_projects#1]
When the video shows that all the letters are boxed in, select the video window and press 'q'
Traceback (most recent call last):
  File "main1.py", line 126, in <module>
    char_img = gray[y:y+h,x:x+w].copy()
TypeError: slice indices must be integers or None or have an __index__ method
[ WARN:0] terminating async callback

i have attached the code file also.

Thanks in advance.......
[main1 - Copy.txt](https://github.com/chedanix/hands_on_projects/files/3157092/main1.-.Copy.txt)

**Comment by chedanix** [comment]
Did you check whether x, y, h, w are actually integers?

**Comment by prasanna532** [comment]
Hi thanks for the reply,
Actually Y value is returning float i have converted that value to int by casting.
But now index error i am getting

When the video shows that all the letters are boxed in, select the video window and press 'q'
*****x: 261 y: 455 h: 28w: 28********
Traceback (most recent call last):
  File "main1.py", line 137, in <module>
    prediction = char_names[np.argmax(predicted_vec)]
IndexError: list index out of range`

I have generated the images char_gen\generated_char_split\train i have around 45 folders...

When the video shows that all the letters are boxed in, select the video window and press 'q'
x: 548 y: 434 h: 17w: 17
x: 276 y: 410 h: 17w: 17
x: 383 y: 386 h: 16w: 16
x: 423 y: 350 h: 28w: 28
Traceback (most recent call last):
  File "main1.py", line 138, in <module>
    prediction = char_names[np.argmax(predicted_vec)]
IndexError: list index out of range

**Comment by prasanna532** [comment]
Problem solved thank you so much.................. :)
